### ISSUE TITLE
Bug: rollout with kubectl breaks

### ISSUE THREAD

**Issue by Avokadoen** [nlnwa/gowarcserver#15]
**Describe the bug**
It seems like badger refuses connection to the new pod with rollout strategy. The scope of fixing this bug might be to big to be worth it.

@maeb can expand this report if he wants (i.e steps to reproduce)

**To Reproduce** 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by maeb** [comment]
The solution to this is to configure deployment with a different strategy so it is deployment specific:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gowarc-server
spec:
  strategy:
    type: Recreate
```
